name: wqm-cdbus
version: "0.7.4"
summary: Can uber dbus
description: |
  Water quality monitoring station
confinement: devmode

apps:
  dosbox:
    command: wqm-candbus

parts:
  dosbox:
    plugin: meson
    source-type: git
    source: http://source.dosbox.com/dosboxsvn.tgz
    build-packages:
      - g++
      - make
      - libsdl1.2-dev
      - libpng12-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
