/*
 * mktbus.h
 *
 *  Created on: 19.01.2015
 *      Author: sascha
 */

#ifndef LC_TERA_MKTBUS_SRC_MKTBUS_H_
#define LC_TERA_MKTBUS_SRC_MKTBUS_H_



/*
 * Autogenerated with `gdbus-codegen`
 */
#include <ultra-pc-generated-code.h>
#include <ultra-can-generated-code.h>
#include <ultra-analogs-generated-code.h>
#include <ultra-sensors-generated-code.h>
#include <ultra-level-generated-code.h>
#include <ultra-errors-generated-code.h>
#include <ultra-measurement-generated-code.h>
#include <ultra-panel-pc.h>
#include <ultra-can-api.h>
#include <ultra-can-dbus.h>
#include <ultra-ams-dbus.h>

// Clien binding
// #include <ultra-can-manager-client.h>
// #include <ultra-pc-manager-client.h>
// #include <ultra-control-dbus-client.h>


#endif
